# Foreground:
#     Fore.BLACK
#     Fore.RED
#     Fore.GREEN
#     Fore.YELLOW
#     Fore.BLUE
#     Fore.MAGENTA
#     Fore.CYAN
#     Fore.WHITE
#     Fore.LIGHTBLACK_EX
#     Fore.LIGHTRED_EX
#     Fore.LIGHTGREEN_EX
#     Fore.LIGHTYELLOW_EX
#     Fore.LIGHTBLUE_EX
#     Fore.LIGHTMAGENTA_EX
#     Fore.LIGHTCYAN_EX
#     Fore.LIGHTWHITE_EX

# Background:
#     Back.BLACK
#     Back.WHITE
#     Back.RED
#     Back.GREEN
#     Back.BLUE
#     Back.YELLOW
#     Back.MAGENTA
#     Back.CYAN
#     Back.LIGHTBLACK_EX
#     Back.LIGHTRED_EX
#     Back.LIGHTGREEN_EX
#     Back.LIGHTYELLOW_EX
#     Back.LIGHTBLUE_EX
#     Back.LIGHTMAGENTA_EX
#     Back.LIGHTCYAN_EX
#     Back.LIGHTWHITE_EX
